<div id="menu1Container">
	<div id="menu1Content" class="menu">
		<div class="options">
			<a href="/advertising/advertising_media.php">request advertising info</a>
			<a href="/advertising"> begin vendor listing </a>
			<a href="/vendor/profile.php?action=edit">edit / update vendor listing</a>
		</div>
	</div>
</div>

<div id="menu2Container">
	<div id="menu2Content" class="menu">
		<div class="options">
			<a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new">Sign-up for Magazine Subscription</a>
			<a href="/subscriptions/subscribe.php?action=edit"> Update / Renew Magazine Subscription</a>
			<a href="/advertising"> begin vendor listing </a>
			<a href="/vendor/profile.php?action=edit">edit / update vendor listing</a>
		</div>
	</div>
</div>

<div id="menu3Container">
	<div id="menu3Content" class="menu">
		<div class="options">
			<a href="/products/index-product.php?localtype=manu_imp&vst=&keyword=&next=0&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Product Search</a>
			<!-- <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=27&searchtype=company">Business Services</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=28&searchtype=company">Computer Software (SW) & Hardware</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1208&ca=no&areacodes=&state=&searchby=nl&searchtype=company">Consultants</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1209&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Equipment: Installation</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1210&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Equipment: Maintenance</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=40&ca=no&areacodes=&state=&searchby=nl&searchtype=company">Equipment: Testing Tools</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=30&searchtype=photo">Erosion Control</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1213&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Irrigation</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=32&searchtype=photo">Lighting / Electrical</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1214&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Outdoor Living</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=33&searchtype=photo">Park &amp; Recreation</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=38&searchtype=photo">Pavers, Masonry, Blocks &amp; Rocks</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1212&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Pest / Wildlife Control</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1216&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Plant Related Chemicals / Fertilizers</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1002&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Planting Accessories</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=29&searchtype=photo">Site Amenities</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1215&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Site Furnishings</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&searchby=nl&next=41&searchtype=photo">Water Features</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1213&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Water Management</a>
            <a class='divider' target='_top' />
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=34&ca=no&areacodes=&state=&searchby=nl&searchtype=company">Plant Material, Turf & Trees</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=35&ca=no&areacodes=&state=&searchby=nl&searchtype=company">Wholesale Equipment & Supplies</a>
            <a href="/products/product_search_keyword.php?localtype=manu_imp&vst=&keyword=&next=1211&ca=no&areacodes=&state=&searchby=nl&searchtype=photo">Wholesale Parts & Supplies</a>
            <a class='divider' target='_top' /> -->

		</div>
	</div>
</div>

<div id="menu4Container">
	<div id="menu4Content" class="menu">
		<div class="options">
        <a href="/tcart/index.php?main_page=product_info&cPath=71&products_id=204">Linked Listings</a>
        <a href="/tcart/index.php?main_page=product_info&cPath=70&products_id=203">Lead Generator</a>
		</div>
	</div>
</div>

<div id="menu5Container">
    <div id="menu5Content" class="menu">
        <div class="options">
            <a href="/research/index.php">Search Articles</a>
            <a href="/research/recent_news.php">Recent News</a>
            <a href="/research/submissions/index.php">Submit Editorial</a>
        </div>
    </div>
</div>

<div id="menu6Container">
    <div id="menu6Content" class="menu">
        <div class="options">
            <a href="/research/LASN-Expo/index-LAE-2012.php">LA Expo - Mar. 30th - 2012</a>
            <a class='divider' target='_top' />
            <a href="/research/TLE/index-tle-2012.php">Landscape Expo - Oct. 10th & 11th - 2012</a>
            <a class='divider' target='_top' />
            <a href="/research/TLE/index-tle-2011.php">Landscape Expo - 2011</a>
        </div>
    </div>
</div>

<div id="menu7Container">
    <div id="menu7Content" class="menu">
        <div class="options">
            <a href="/industry/index.php">Find an Association</a>
            <a href="/calendar/index.php">Search for Events</a>
			<a class='divider' target='_top' />
            <a href="/industry/associat_list.php">List Your Association / Event</a>
            <a href="/industry/associat_list.php?action=edit">Edit Your Association / Event</a>
            <a href="/industry/suggest.php">Suggest an Association</a>
			<a class='divider' target='_top' />
			<a href="/TLE-LB/index-tle-2017.php">TLE - Long Beach - Oct. 4-5</a>
		</div>
    </div>
</div>

<div id="menu8Container">
    <div id="menu8Content" class="menu">
        <div class="options">					
            <a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new">New Subscription Request</a>
            <a href="/subscriptions/subscribe.php?action=edit">Renew/Update Subscriber Info</a>
            <a class='divider' target='_top' />
            <a href="/vendor/signup/index2.php">New Vendor / Services Listing</a>
            <a href="/vendor/profile.php?action=edit">Update Vendor / Services Listing</a>
            <a href="/vendor/profile.php?action=edit">Sales Lead Retrival</a>
            <a class='divider' target='_top' />
            <a href="/industry/associat_list.php">List Your Association</a>
            <a href="/industry/associat_list.php?action=edit">Edit Your Association</a>
        </div>
    </div>
</div>

<div id="menu9Container">
    <div id="menu9Content" class="menu">
        <div class="options">
            <a href="/contact/index.php">General Info</a>
            <a href="/advertising/advertising_media.php">Advertising Info</a>
            <a href="/guideinfo/index.php">Product Guide Info</a>
            <a href="/research/submissions/index.php">Submit Editorial</a>
           <a class='divider' target='_top' />
            <a href="/subscriptions/subscribe.php?action=new">Subscriber Sign-up</a>
            <a href="/vendor/signup/index2.php">Vendor Sign-up</a>			
      </div>
    </div>
</div>
