<div id="lol_header">
    <div id="lol_logo">
        <a href="/"><img border='0' height="60" width="270" src="/imgz/main_lol_logo.gif" alt="LandscapeOnline.com" /></a>
    </div>
    <div id="lol_bannerTop"> <? $C->banner($_SERVER['PHP_SELF'],1); ?> </div>
</div>

<div id="menubar">
    <table width='100%' cellpadding='0' cellspacing='0' border='0'>
        <tr valign='top' align='center'>
	    <td width='125'><a id="act2" onmouseover="ypSlideOutMenu.showMenu('menu3')" onmouseout="ypSlideOutMenu.hideMenu('menu3')">Product Search</a></td>
	    <td width='125'><a id="act3" onmouseover="ypSlideOutMenu.showMenu('menu4')" onmouseout="ypSlideOutMenu.hideMenu('menu4')">Find A Pro</a></td>
	    <td width='125'><a id="act4" href="/research" onmouseover="ypSlideOutMenu.showMenu('menu5')" onmouseout="ypSlideOutMenu.hideMenu('menu5')">Articles/News</a></td>
	    <td width='100'><a id="act6" href="/calendar" onmouseover="ypSlideOutMenu.showMenu('menu7')" onmouseout="ypSlideOutMenu.hideMenu('menu7')">Industry Links</a></td>
	    <td width='100'><a id="act7" onmouseover="ypSlideOutMenu.showMenu('menu8')" onmouseout="ypSlideOutMenu.hideMenu('menu8')">Sign-Up</a></td>
	    <td width='125'><a id="act8" href="/contact" onmouseover="ypSlideOutMenu.showMenu('menu9')" onmouseout="ypSlideOutMenu.hideMenu('menu9')">Contact Us</a></td>
       </tr>
    </table>
</div>
