<!-- <?=__FILE__ ?> Begin -->

	<TABLE width="102" cellpadding="0" cellspacing="0">
		<TR>
			<TD valign="top" width=2 rowspan="5">&nbsp;</td>
			<TD valign="top"> 
					<TABLE style="position: relative; margin-top: -3px;" width="100" cellpadding="0" cellspacing="3">
		<TR><TD valign="center" align="center"><? $C->banner($PHP_SELF,6) ?></TD></TR>
		<TR><TD valign="center" align="center"><? $C->banner($PHP_SELF,7) ?></TD></TR>
		<TR><TD valign="center" align="center"><? $C->banner($PHP_SELF,8) ?></TD></TR>
		<TR><TD valign="center" align="center"><? $C->banner($PHP_SELF,9) ?></TD></TR>
		<tr valign=top><td><table cellpadding="3" cellspacing="0"><?=$leftpane?></table><br></td></tr>
		<? if (!$nolbads) { ?> 

		
		<? } ?>
						
						
						
						
					</TABLE>
			</TD>
		</TR>

	</TABLE></div>

<!-- <?=__FILE__ ?> End -->
