 <?





?>

<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>

  <!-- Basic Page Needs -->
  <meta charset="utf-8">
  <title>Bad Tree Comic</title>
    
<meta name="description" content="Home of Bad Tree Comic and Friends. Always good for a laugh. I was working on an article, Bad Trees! Identifying at Risk Trees and created an image of Bad Tree for the article. It made the cover and from there BT was born.">
<meta name="keywords" content="bad tree,bamboo,tikis,bad tree comic">
<meta name="author" content="Jerry Short">
<meta name="title" content="Bad Tree Comic Featured Comics Monday and Thursday by Jerry Short">
<meta property="og:title" content="Bad Tree Comic: Life According to Bad Tree - by Jerry Short" />
<meta property="og:description" content="Home of Bad Tree Comic and Friends. Always good for a laugh. I was working on an article, Bad Trees! Identifying at Risk Trees and created an image of Bad Tree for the article. It made the cover and from there BT was born."/>	
<meta property="og:url" content="https://landscapearchitect.com/bad-tree/index.php" />
<meta name='twitter:Bad Tree'>
<meta property="og:type" content="comic" />
	<meta property="og:image" content="https://landscapearchitect.com/bad-tree/comics/bad-tree-med-2018-06f.jpg" />
    <meta name='twitter:Bad Tree'>	
<title>Bad Tree Comic Featured Comics Monday and Thursday by Jerry Short</title>    

  <!-- Mobile Specific Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- CSS Style -->
  <link rel="stylesheet" href="/bad-tree/css/style3.css"> 
  
  <!-- Color Skins -->
  <link rel="stylesheet" href="/bad-tree/css/skins/blue.css" name="skins"> 
  
  <!-- Layout Style -->
  <link rel="stylesheet" href="/bad-tree/css/layout/wide.css" name="layout"> 
  
  <!-- Style Switcher Box -->
  <link rel="stylesheet" href="/bad-tree/css/layout/switcher.css">
  
  <!-- Small Icons -->
  <link rel="stylesheet" href="/bad-tree/css/icons.css">  
  
  <!-- Start JavaScript -->
  
    <script src="/bad-tree/js/jquery-1.7.2.min.js"></script> <!-- jQuery library -->
    <script src="/bad-tree/js/jquery.easing.1.3.min.js"></script> <!-- jQuery Easing --> 
    <script src="/bad-tree/js/jquery-ui.min.js"></script> <!-- jQuery Ui --> 
    <script src="/bad-tree/js/jquery.cookie.js"></script> <!-- jQuery cookie --> 
    <script src="/bad-tree/js/jquery.uniform.min.js"></script> <!-- jQuery Uniform -->
    <script src="/bad-tree/js/ddsmoothmenu.js"></script> <!-- Nav Menu ddsmoothmenu -->
    <script src="/bad-tree/js/jquery.flexslider.js"></script> <!-- Flex Slider  -->
    <script src="/bad-tree/js/jquery.eislideshow.js"></script> <!-- Elastic Slider  -->
    <script src="/bad-tree/js/jquery.iconmenu.js"></script> <!-- Sliding Text and Icon Menu Style  -->
    <script src="/bad-tree/js/colortip.js"></script> <!-- Colortip Tooltip Plugin  -->
    <script src="/bad-tree/js/tytabs.js"></script> <!-- jQuery Plugin tytabs  -->
    <script src="/bad-tree/js/carousel.js"></script> <!-- jQuery Carousel  -->
    <script src="/bad-tree/js/jquery.prettyPhoto.js"></script> <!-- jQuery Prettyphoto  -->
    <script src="/bad-tree/js/jquery.isotope.min.js"></script> <!-- Isotope Filtering  -->
    <script src="/bad-tree/js/selectnav.js"></script> <!-- Responsive Navigation Menu by SelectNav -->
    <script src="/bad-tree/js/jquery.ui.totop.js"></script> <!-- UItoTop plugin  -->
    <script src="/bad-tree/js/custom.js"></script> <!-- Custom Js file for javascript in html -->
    <script src="/bad-tree/js/jquery.tweet.js"></script> <!-- jQuery Tweets -->
    <script src="/bad-tree/js/jflickrfeed.min.js"></script> <!-- jQuery Flickr -->
    <script src="/bad-tree/js/twitter-flickr-options.js"></script> <!-- jQuery Tweets Options -->
    <script src="/bad-tree/js/styleswitch.js"></script> <!-- Style Switcher -->
  
  <!-- End JavaScript -->

  <!--[if lt IE 9]>
      <script src="/bad-tree/js/html5.js"></script>
  <![endif]-->

  <!-- Favicons -->
  <link rel="shortcut icon" href="/bad-tree/images/favicon/favicon.ico">
  <link rel="apple-touch-icon" href="/bad-tree/images/favicon/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/bad-tree/images/favicon/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/bad-tree/images/favicon/apple-touch-icon-114x114.png">

</head>
<body>

