						<section>
							<div class="row">
								<div class="col-md-3 col-sm-offset-2">

									<section>
										<center><span class="icon featured fa-sitemap "></span></center>

										<p>Need to view more product categories:<br /><a href="https://landscapearchitect.com/products/index-product-search.php" target="_blank">Read more</a></p>
									</section>

								</div>
								<div class="col-md-3">

									<section>
										<center><span class="icon featured fa-tasks"></span></center>

										<p>If you need to sign up as a vendor or update your vendor profile:<br /><a href="https://landscapearchitect.com/vendor/signup/index2.php" target="_blank">Read more</a></p>
									</section>

								</div>
								<div class="col-md-3">

									<section>
										<center><span class="icon featured fa-book"></span></center>

										<p>How about siging up for a Magazine or update your subscriber profile:<br /><a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new" target="_blank">Read more</a></p>
									</section>

								</div>
							</div>
						</section>