						<section>
							<div class="row">
							
								<div class="col-md-2">
									<section>
										<img width="60%" src="images/pic01.jpg" alt="image">
									</section>
								</div>
								
								<div class="col-md-2">
									<section>
										<img width="60%" src="images/pic01.jpg" alt="image">
									</section>
								</div>
								
								<div class="col-md-2">
									<section>
										<img width="60%" src="images/pic01.jpg" alt="image">
									</section>
								</div>
								
								<div class="col-md-2">
									<section>
										<img width="60%" src="images/pic01.jpg" alt="image">
									</section>
								</div>
								
								<div class="col-md-2">
									<section>
										<img width="60%" src="images/pic01.jpg" alt="image">
									</section>
								</div>
								
								<div class="col-md-2">
									<section>
										<img width="60%" src="images/pic01.jpg" alt="image">
									</section>
								</div>								
								
							</div>
						</section>