<?


?>


                <section style="text-align: center; position: relative;">
							<div class="row">
								<div class="col-md-3" style="text-align: center; position: relative; left: 25px">

										<center><span class="icon featured fa-users"></span></center>

										<center><p>We Support<br />LO financially supports<br><a href="https://landscapearchitect.com/products/index-product-search.php" target="_blank">Read more</a></p></center>

								</div>
								<div class="col-md-3">

										<center><span class="icon featured"><a href="/bad-tree/index.php" target="_blank"><img src="https://landscapearchitect.com/imgz/bad-tree-banner-sm.gif" width="60%" border="0" /></a></span></center>

										<center><p>Bad Tree Comic. Check it out:<br />New Comics Every Monday &amp; Thursday<br /><a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new" target="_blank">Read more</a></p></center>

								</div>
								<div class="col-md-3">


										<center><span class="icon featured "><!-- <a href="/lcc/lcc.html" target="_blank"> --><img width="50px" src="https://landscapearchitect.com/imgz2/fish.jpg"><!-- </a> --></span></center>

										<center><p>If interested in finding out more:<br /><!-- <a href="/lcc/lcc.html" target="_blank"> -->Read more<!-- </a> --></p></center>                                    
                                    

								</div>
							</div>
						</section>