						<section>
							<div class="row">
								<div class="col-md-3 col-sm-offset-2">

									<section>
										<center><span class="icon featured fa-phone-square"></span></center>

										<p>Need more information of help. Please feel free to contact us at LandscapeOnline:<br /><a href="https://landscapearchitect.com/template-contact-a.php" target="_blank">Read more</a></p>
									</section>

								</div>
								<div class="col-md-3">

									<section>
										<center><span class="icon featured fa-pencil-square"></span></center>

										<p>Have a story or interesting project, that you would like to submit for article consideration:<br /><a href="https://landscapearchitect.com/research/recent_news.php" target="_blank">Read more</a></p>
									</section>

								</div>
								<div class="col-md-3">

									<section>
										<center><span class="icon featured fa-users"></span></center>

										<p>Have an association or event you need to list:<br /><a href="https://landscapearchitect.com/research/recent_news.php" target="_blank">Read more</a></p>
									</section>

								</div>
							</div>
						</section>