<?



?>


						<section>
							<div class="row">
								<div class="col-md-3 col-sm-offset-2">

									<section>
										<center><span class="icon featured fa-users"></span></center>

										<center><p>We Support<br />LO financially supports<br><a href="https://landscapearchitect.com/products/index-product-search.php" target="_blank">Read more</a></p></center>
									</section>

								</div>
								<div class="col-md-3">

									<section>
										<center><span class="icon featured "><a href="/lcc/lcc.html" target="_blank"><img width="30%" src="https://landscapearchitect.com/imgz2/fish.jpg"></a></span></center>

										<center><p>If interested in finding out more:<br /><a href="https://landscapearchitect.com/vendor/signup/index2.php" target="_blank">Read more</a></p></center>
									</section>

								</div>
								<div class="col-md-3">

									<section>
										<center><span class="icon featured"><a href="/bad-tree/index.php" target="_blank"><img src="https://landscapearchitect.com/imgz/bad-tree-banner-sm.gif" width="60%" border="0" /></a></span></center>

										<center><p>Bad Tree Comic. Check it out:<br /><a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new" target="_blank">Read more</a></p></center>
									</section>

								</div>
							</div>
						</section>