<?
									

				  $servername = "localhost";
                  $username = "land_patchew";
                  $password = "59q2GB6k$3";
                  $dbname = "land_landscap_lollive";

					// Create connection
						$conn = new mysqli($servername, $username, $password, $dbname);
					// Check connection
							if ($conn->connect_error) {
								die("Connection failed: " . $conn->connect_error);
							} 
									
									
									
									
									
									
?>