
<?


?>

            <!-- FOOTER -->
            <footer style="clear: both;">
                <div class="container" style="clear: both;">
                    <div class="row text-center">
                        <p style="margin-bottom: 5px;"><a href="#">Products</a> | <a href="#">Advertising</a> | <a href="#">Become A Vendor</a> | <br class="mob-only" style="display:none;" /><a href="#">Contact Us</a> | <a href="#">About Us</a></p>
						<p style="margin-bottom: 0px;"><a href="#">Careers</a> | <a href="#">Awards</a> | <a href="#">Subscribe</a> | Landscape Communications Inc. © 2019</p>
                    </div>
                </div>
            </footer>

            

        </div>

        

        <div id="backtotop"><i class="fa fa-chevron-up"></i></div>

        <!-- Javascript -->
        <script src="../LandscapeProducts/js/jquery.js"></script>

        <!-- ADDTHIS -->
        <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
        <script type="text/javascript">
                                            // Call this function once the rest of the document is loaded
                                            function loadAddThis() {
                                                addthis.init()
                                            }
        </script>

        <!-- ADDTHIS -->
        <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-557a95e76b3e51d9" async="async"></script>
        <script type="text/javascript">
                                            // Call this function once the rest of the document is loaded
                                            function loadAddThis() {
                                                addthis.init()
                             
               }
        </script>
            
        <script src="../LandscapeProducts/js/bootstrap.min.js"></script>        
        <script src="../LandscapeProducts/plugin/owl-carousel/owl.carousel.min.js"></script>
        <script src="../LandscapeProducts/js/bs-navbar.js"></script>
        <script src="../LandscapeProducts/js/vendors/isotope/isotope.pkgd.js"></script>
        <script src="../LandscapeProducts/js/vendors/slick/slick.min.js"></script>
        <script src="../LandscapeProducts/js/vendors/tweets/tweecool.min.js"></script>
        <script src="../LandscapeProducts/js/vendors/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
        <script src="../LandscapeProducts/js/vendors/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
        <script src="../LandscapeProducts/js/jquery.sticky.js"></script>
        <script src="../LandscapeProducts/js/jquery.subscribe-better.js"></script>
        <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
        <script src="../LandscapeProducts/js/vendors/select/jquery.selectBoxIt.min.js"></script>
				<script src="../LandscapeProducts/js/jquery.validate.min.js"></script>
        <script src="../LandscapeProducts/js/main.js"></script>
						
			


<!-- New Tracking -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2956957-3', 'auto');
  ga('send', 'pageview');

</script>    

		