<? if($pageId == "home"){ ?>	

  <style>
    .ader {
      margin-bottom: 0px !important;
      margin-top: -7px !important;
    }
  </style>

<? } ?>


<div class="container text-center hidden-xs hidden-sm" style="padding-bottom: 20px;" id="leaderboard-banner-container">
	<span class="ader">ADVERTISEMENT </span>
    <div class="add_nn">
				 <!-- banner ad leaderboard -->
				<?
					
//						 $servername = "localhost";
//						$username = "land_patchew";
//						$password = "59q2GB6k$3";
//						$dbname = "land_landscap_lollive";
//
//					// Create connection
//						$conn = new mysqli($servername, $username, $password, $dbname);
//					// Check connection
//						if ($conn->connect_error) {
//								 die("Connection failed: " . $conn->connect_error);
//						} 
//
//				
//				
//					$sql = "SELECT * FROM banner_ups WHERE ROS='lad' ORDER BY RAND() LIMIT 1";
//					$result = $conn->query($sql);									

//					while($row = mysqli_fetch_array($result)){
//							echo '<a href="' .  $row['web'] . '"><img src="https://landscapearchitect.com/banner/'  . $row['picture'] . '" class=" hidden-xs hidden-sm" style="width:100%;" /></a> '; 
//					}

				?>
      <? if($pageId == "home"){ ?>
      
  
        <button id="close-banner" style="position: relative; float: right; background: none; border: none; width: 30px;  height: 30px; padding: 0px; margin-bottom: -25px;"><i class="fa fa-close" style=" width: 11px; height: 11px; color:white; -webkit-text-stroke: 1.5px #103c05; font-size: 20px;"></i></button>

      <? } ?>
        
      
      <a href="http://www.landscapearchitect.com/research/Ad-Transfer/transfer/RD1816LA2001AdTrans.html"><img src="https://landscapearchitect.com/banner/RD1816LA2001-1.jpg" style="width: 100%;" /></a>
      
		
    </div><!-- /.add_nn -->
</div><!-- /.contianer -->