<?



?>


  <!-- Main Navigation -->  
  <div class="row main-navigation">
    <div class="large-12 columns">			

      <nav class="top-bar">
        <ul class="title-area">
          <!-- Title Area -->
          <li class="name"></li>
          <!-- Menu Icon -->
          <li class="toggle-topbar menu-icon"><a href="#"><span> </span></a></li>
        </ul>

        <section class="top-bar-section">
        <!-- Left Nav Section -->
          <ul class="left">
            <li class="divider"></li>
            <li class="has-dropdown"><a class="active" href="index.php">Home</a>
              <ul class="dropdown">
                <li><a href="index.php">Home</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="has-dropdown"><a href="#">LA Details</a>
              <ul class="dropdown">
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=28" >Business Services &amp; Software</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist28() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=30">Erosion Control</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist30() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1300">Fencing</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1300() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1213">Irrigation / Warter Mgmt.</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1213() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=32">Lighting / Electircal</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist32() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1214">Outdoor Living</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1214() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=33">Park &amp; Recreation</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist33() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=38">Paver, Masonry, Blocks, Rocks</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist38() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1212">Pest / Wildlife</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1212() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1002">Plant Accessories &amp; Amendments</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1002() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1301">Sculpture/Art/Garden Ornaments</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1301() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=29">Site Amenities</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist29() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=1215">Site Furnishings &amp; Receptacles</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist1215() ?> 
                          
                      </ul>                    
                </li>
                <li class="has-dropdown"><a href="https://landscapearchitect.com/responsive/Matte2/html/la-details-top-category.php?ad=41">Water Features</a>
                      <ul class="dropdown">
                        
                         <? tablecatlist41() ?> 
                          
                      </ul>                    
                </li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="has-dropdown"><a href="#">Articles &amp; Research</a>
              <ul class="dropdown">
                <li><a href="#" >Search Landscape Articles</a></li>
                <li><a href="#">Digital Landscape Magazines</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/recent-news.php">Top Stories of the Week</a></li>
                <li><a href="#">Featured Products</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/recent-news.php#recentnews">Recent News</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/recent-news.php#landscapeLegislation">More Landscape Legislation News</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/recent-news.php#association">More Association News</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/recent-news.php#education">More Education News</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/recent-news.php#economic">More Economic News</a></li>
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/editoral-submissions.php">Submit Editoral</a></li>
              </ul>
            </li>                    
            <li class="divider"></li>
            <li class="has-dropdown"><a href="#">Login/Sign-Up</a>
              <ul class="dropdown">
                <li><a href="https://landscapearchitect.com/responsive/Matte2/html/new-subscription.php">New Subscription</a></li>
				<li><a href="#">Renew Subscription</a></li>
				<li><a href="#">Link</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="has-dropdown"><a href="#">Landscape Expo</a>                                        
              <ul class="dropdown">                        
                <li><a href="https://landscapearchitect.com/TLE-LB/index-tle-2018.php">Landscape Expo Home</a></li>
                <li><a href="#">Expo Registration Opens Spring 2019</a></li>
                <li><a href="https://landscapearchitect.com/TLE-LB/Call-for-speakers-2019.php">Landscape Seminars - Call For Speakers</a></li>
                <li><a href="https://landscapearchitect.com/TLE-LB/exhibitor-List-2019.php">Exhibitor List - 2019 Exhibitors</a></li>
                <li><a href="https://landscapearchitect.com/TLE-LB/exhibitor-signup-2019.php">Exhibitor Sign-Up</a></li>
                <li><a href="https://landscapearchitect.com/TLE-LB/floor-plan-2019.php">Floor Plan</a></li>
                <li><a href="https://landscapearchitect.com/TLE-LB/contact_us-2019.php">Contact The Show</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="has-dropdown"><a href="#">Blog</a>                    
              <ul class="dropdown">
                <li><a href="https://landscapearchitect.com/lmb2/">Blog Default</a></li>
                <li><a href="#">Blog Inner</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li><a href="contact.php">Contact Us</a></li>
          </ul>
          <!-- End Left Nav Section -->

          <!-- Right Nav Search -->
          <!--
          <ul class="right">
            <li class="has-form">
              <form>
                <div class="row collapse">
                  <div class="small-8 columns">
                    <input type="text">
                  </div>
                  <div class="small-4 columns">
                    <a href="#" class="button expand">Search</a>
                  </div>
                </div>
              </form>
            </li>
          </ul>
          -->
          <!-- End Right Nav Search -->
    
        </section>
      </nav>

    </div>
  </div>
  <!-- End Main Navigation -->
    