<?

?>

<!-- Horizontal Bar Start -->
<div style="position:relative; left:0px; top:25px; padding:0px; width:750px; height:2px; background-color:#605b51;"></div>
<!-- Horizontal Bar End -->


 
 <!-- Social Links -->
 <div align="center" style="position:relative; left:-40px; top:25px; padding-top: 0px"><br>
	<table width="400" cellspacing="10">
        <tr>
        	<td align="center" colspan="4"><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:bold">Follow us: </span></td>
        </tr>    
    	<tr>
        	<td align="center"><a href="https://www.facebook.com/LASNMagazine/" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/facbook-logo.jpg" width="25" height="25" /></a></td>
            <td align="center"><a href="https://twitter.com/LandscapeASN" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/Twitter_logo_blue.jpg" width="25" height="25" /></a></td>
            <td align="center"><a href="https://www.linkedin.com/showcase/landscape-architect-and-specifier-news" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/linkedinicon.jpg" width="25" height="25" /></a></td>
            <td align="center"><a href="https://www.instagram.com/landscapeasn/" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/instagramicon.jpg" width="25" height="25" /></a></td>
        </tr>
        <tr style="font-family:Arial, Helvetica, sans-serif; font-size:11px;">
        	<td align="center">
            <a href="https://www.facebook.com/LASNMagazine/" target="_blank">@LASNMagazine</a>
            </td>
        	<td align="center">
            <a href="https://twitter.com/LandscapeASN" target="_blank">@LandscapeASN</a>
            </td>
        	<td align="center">
            <a href="https://www.linkedin.com/showcase/landscape-architect-and-specifier-news" target="_blank">@ Landscape Architect and Specifier News</a>
            </td>
        	<td align="center">
            <a href="https://www.instagram.com/landscapeasn/" target="_blank">@LandscapeASN</a>
            </td>
        </tr>
 	</table>       
</div>

<!-- Footer Section Start --> 
<div align="center" style="position:relative; left:-50px; top:25px;">
	<table>
		<tr>
			<td align="center" colspan="5">	
	    	<br />
	    	<? date_default_timezone_set("America/Los_Angeles"); ?>
	    	<?= date("F j, Y, g:i a "); ?>PDT
        	<p>
            Website problems, <a href="https://landscapearchitect.com/bug/bug-report.php" target="_blank">report a bug</a>.<br />
            Copyright &copy; 2019 Landscape Communications Inc.<br />
        	</p><br />
	    	<? if ($_SESSION['uid']){ ;?><!-- <FONT size="-2"><a href="/kill.php">Sign Out</a></font> -->
	    	<img src="/imgz/spacer.gif" width=10 height=10 onMouseOver="window.status='uid=<?=$_SESSION['uid']?>'; return true;" onMouseOut="window.status=''"><? } ?>
			</td>
		</tr>
</table>
</div>

<!-- We support -->
<div style="position:relative; left:50px; top:15px; padding: 0px; width: 200px; font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-weight: bold">

<table width="750px">
	<tr>
		<td style="width: 150px">
			<center>We Support<br>
				<span style="font-size: 11px"><a href="https://landscapearchitect.com/research/article-a.php?number=8306">LO financially supports many associations through either the payment of dues, conference exhibits and/or discounted advertising</a></span></center>
		</td>
		<td style="width: 125px">&nbsp;</td>
		<td>
			<a href="/lcc/lcc.html" target="_blank"><img src="https://landscapearchitect.com/imgz2/fish.jpg" width="46" height="28"></a>
		</td>
		<td style="width: 5px">&nbsp;</td>
		<td>
				<center><a href="/bad-tree/index.php" target="_blank"><img src="https://landscapearchitect.com/imgz/bad-tree-banner-sm.gif" width="200" height="52" border="0" /></a><br>
					Last Updated 07-08-19<br>
					New Comic Every Monday &amp; Thursday.</center>
		</td>		
	</tr>
</table>

</div>


<div style="position:relative; left:300px; top:25px;">
	<script type="text/javascript" src="https://sealserver.trustwave.com/seal.js?style=normal"></script>
</div>
<!-- Footer Section Start --> 