<div class="bottom1">
	<? // include $include_path . "lo_footer-main2-front.inc"; ?>
   
   
 
   
   
    
<!-- New Tracking -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-2956957-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
 
  gtag('config', 'UA-2956957-3');
</script>
    
</div>
