<?
   session_start();

   include("land-design-meta.inc");
    include("lad_common.inc");

?>



  <!-- Break for top start --> 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<meta name="keyword" content="<? echo $keyword; ?>">
<!-- Bootstrap -->
<link rel="stylesheet" href="https://landscapearchitect.com/css/bootstrap-LA.css">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	
<script src='https://www.google.com/recaptcha/api.js'></script>
	
<?php
// Important! You have to include it before your html code
include_once "/home/land/public_html/advpoll/poll_cookie.php";
?>	
	
	
</head>
<body>
    

    
    
	
  <!-- Break for top end -->
	
	
	