<?
    if(isset($_GET['catMain']))
    {
        $value = $_GET['catMain'];
    }
    switch($value) {
        case 'Fencing':
            $title = 'Wholesale Metal & Chain Link Fencing | LandscapeOnline';
            $metakeyword = 'Wholesale Fencing, wholesale chain link fence, wholesale metal fencing';
            $searchbartitle = 'Wholesale Metal & Chain Link Fencing';
        break;
        case 'Lighting/Electrical':
            $title = 'Commercial Exterior Lighting & Electrical | LandscapeOnline';
            $metakeyword = 'Commercial Exterior Lighting';
            $searchbartitle = 'Commercial Exterior Lighting & Electrical';
        break;
        case 'Outdoor Living':
            $title = 'Outdoor Living & Landscaping Design | LandscapeOnline';
            $metakeyword = 'Outdoor Living Design';
            $searchbartitle = 'Outdoor Living and Landscaping Design';
        break;
        case 'Paver, Masonry, Blocks, Rocks':
            $title = 'Commercial Pavers, Masonry, Blocks, Rocks | LandscapeOnline';
            $metakeyword = 'Commercial Pavers';
            $searchbartitle = 'Commercial Pavers, Masonry, Blocks, Rocks';
        break;
        case 'Site Amenities':
            $title = 'Commercial Site Amenities | LandscapeOnline';
            $metakeyword = 'Commercial Site Amenities';
            $searchbartitle = 'Commercial Site Amenities';
        break;
        case 'Sculpture/Art/Garden Ornaments':
            $title = 'Commercial Sculptures, Landscape Art, Metal & Stone Garden Ornaments | LandscapeOnline';
            $metakeyword = 'Commercial Sculptures, Landscape Art, Stone Garden Ornaments, Metal Garden Ornaments';
            $searchbartitle = 'Commercial Sculptures, Landscape/ Art, Metal & Stone Garden Ornaments';
        break;
        case 'Site Furnishings and Receptacles':
            $title = 'Commercial Site Furnishings and Receptacles | LandscapeOnline';
            $metakeyword = 'Commercial Site Furnishings, Commercial Waste Receptacles';
            $searchbartitle = 'Commercial Site Furnishings and Commercial Waste Receptacles';
        break;
        case 'Park and Recreation':
            $title = 'Parks and Recreation Design & Products | LandscapeOnline';
            $metakeyword = 'Park Designs';
            $searchbartitle = 'Parks and Recreation Designs & Products';
        break;
        case 'Water Features':
            $title = 'Water Feature Design Products | LandscapeOnline';
            $metakeyword = 'Water Feature Design Products';
            $searchbartitle = 'Water Feature Design Products';
        break;
        case 'Business Services & Software':
            $title = 'Business Services & Commercial Landscape Design Software | LandscapeOnline';
            $metakeyword = 'Commercial Landscape Design Software';
            $searchbartitle = 'Business Services & Commercial Landscape Design Software';
        break;
        case 'Business Services ':
            $title = 'Business Services & Commercial Landscape Design Software | LandscapeOnline';
            $metakeyword = 'Commercial Landscape Design Software';
            $searchbartitle = 'Business Services & Commercial Landscape Design Software';
        break;
        case 'Erosion Control':
            $title = 'Landscape Erosion Control Products | LandscapeOnline';
            $metakeyword = 'Landscape Erosion Ccontrol Products';
            $searchbartitle = 'Landscape Erosion Control Products';
        break;
        case 'Pest/Wildlife':
            $title = 'Wildlife & Commercial Landscape Pest Control | LandscapeOnline';
            $metakeyword = 'Commercial Landscape Pest Control';
            $searchbartitle = 'Wildlife & Commercial Landscape Pest Control';
        break;
        case 'Plant Accessories & Amendments':
            $title = 'Wholesale Plant Accessories & Soil Amendments | Landscape Online';
            $metakeyword = 'Wholesale Plant Accessories, Soil Amendments';
            $searchbartitle = 'Wholesale Plant Accessories & Soil Amendments';
        break;
        case 'Plant Accessories ':
            $title = 'Wholesale Plant Accessories & Soil Amendments | Landscape Online';
            $metakeyword = 'Wholesale Plant Accessories, Soil Amendments';
            $searchbartitle = 'Wholesale Plant Accessories & Soil Amendments';
        break;
        case 'Water Management':
            $title = 'Landscape Water Management';
            $metakeyword = 'Landscape Water Management';
            $searchbartitle = 'Landscape Water Management';
        break;

    }
?>