<?
$number = $_GET['number'];
    switch($number){
        case '43260':
            $title = 'Wear-N-Tear® Turf Mix | Erosion Control Products | LandscapeOnline';
            $keyword = 'Erosion Control Products';
            break;
        case '42289':
            $title = 'Incon Lighting | Landscape Lighting Manufacturer | LandscapeOnline';
            $keyword = 'Landscape Lighting Manufacturer';
            break;
        case '4735':
            $title = 'Jacaranda ‘Bonsai Blue’ | Wholesale Plant Products | LandscapeOnline';
            $keyword = 'Wholesale Plant Products';
            break;
   }
?>