<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;CHARSET=x-mac-roman">

<title>
Lead Generator Tool
</title>

</head>

<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">

<form action="compfind.php" method="POST">
	<div style="position:absolute; left:255px; top:760px; padding:0px; width:500px; height:30px">
		<label for="firstname">Company code:</label>
		<input type="text" id="id" name="id" />
	</div>
	<div style="position:absolute; left:255px; top:790px; padding:0px; width:500px; height:30px">
		<label for="lastname">Last name:</label>
		<input type="text" id="lastname" name="lastname" />
	</div>		
<div style="position:absolute; left:245px; top:820px; padding:0px; width:500px; height:30px">
		<label for="email">Email Address:</label>
		<input type="text" id="email" name="email" />
	</div>		
	<div style="position:absolute; left:247px; top:850px; padding:0px; width:500px; height:30px">
		<input type="submit" value="Submit" name="submit" />
	</div>
</form>


	
