<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;CHARSET=x-mac-roman">

<title>

</title>
<style type="text/css">
<!-- 
    a:link {
        color:blue;
        text-decoration:underline;
    }
    a:active { color:red }
    a:visited { color:purple }
    body {
        background-color:white;
        color:black;
    }
    .text0 {
        font-family:'Helvetica','Arial','Sans-serif';
        font-size:11px;
        text-decoration:none;
        color:black;
    }
    .text06 {
        font-family:'Helvetica','Arial','Sans-serif';
        font-size:11px;
    }
    .para0 {
        text-align:left;
    }
    .box1 {
        background-color:white;
        width:763px;
        height:1400px;
    }
    .box2 {
        position:absolute;
        left:325px;
        top:365px;
        padding:0px;
        width:274px;
        height:30px;
    }
    .box3 {
        position:absolute;
        left:528px;
        top:632px;
        padding:0px;
        width:274px;
        height:30px;
    }
    .box4 {
        position:absolute;
        left:285;
        top:692px;
        padding:0px;
        width:274px;
        height:30px;
    }
 -->
</style>
</head>

<body>

<div align="center" style="position: absolute; left:5px; top:-14px"> 

	<div style="width:750px; font-family:Arial, Helvetica, sans-serif; font-size:16px">
		<span style="font-size:32px; font-weight:bold; font-family:Arial, Helvetica, sans-serif">Welcome to the</span><br><br>
	<center><img src="https://landscapearchitect.com/lol-logos/LASN_BLUE_500.jpg" width="280" align="top" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://landscapearchitect.com/lol-logos/lcdbms-logo-NEW-BIG-2.jpg" width="295" align="top" /></center>
    <center><img src="https://landscapearchitect.com/lol-logos/lolw-logo.jpg" width="300" /></center><br />
	<span style="font-size:32px; font-weight:bold">Subscription Management Center</span><br></p>
	</div>
		
	<div style="width:600px; font-family:Arial, Helvetica, sans-serif; font-size:24px; line-height: 1.5em">
		<strong>Find My Password</strong><br>


<form action="mailback.php" method="POST">
<div style="position:absolute; left:10px; top:330px; width:750px; font-family:Arial, Helvetica, sans-serif; font-size:16px">
		<i>Please fill out the form below and it will be emailed to you. <br>
		(*All fields are required)</i>
	</div>

<form action="mailback.php" method="POST">
	<div align="left" style="position:absolute; left:265px; top:390px; padding:0px; width:500px; height:30px">
		<label for="firstname"><font size="3">First name:</font></label>
		<input type="text" id="firstname" name="firstname" size="35" />
	</div>
	<div align="left"  style="position:absolute; left:266px; top:410px; padding:0px; width:500px; height:30px">
		<label for="lastname"><font size="3">Last name:</font></label>
		<input type="text" id="lastname" name="lastname" size="35" />
	</div>		
<div align="left" style="position:absolute; left:237px; top:440px; padding:0px; width:500px; height:30px">
		<label for="email"><font size="3">Email Address:</font></label>
		<input type="text" id="email" name="email" size="35" />
	</div>		
	<div align="left" style="position:absolute; left:355px; top:475px; padding:0px; width:500px; height:30px">
		<input type="submit" value="Submit" name="submit" />
	</div>
</div>
</form>


