<div id='pageBody'>
<table width="100%" cellpadding="0" cellspacing="0">
	<tr>
		<td>
			<img src="/lol-logos/LO-LOW-logo-325.jpg" width="325"><br /><br />
		</td>
	</tr>
	<tr>
		<td>
			<TABLE>
				<TR>
					<TD>
					  <strong><u>Contact Your Advertising Sales Representative:</u></strong><br>
              <br />
              <table border="0" cellpadding="" cellspacing="0">
                    <tr>
                        <td>Nathan Schmok<br />
<a href="mailto:nschmok@landscapeonline.com?subject=LandscapeOnline Advertising Information Request">(714) 979-5276 x143</a>
                        <br /><br />
                    <strong><u>Editorial:</u></strong><br>
                          <A href="https://landscapearchitect.com/research/letter_sub.php">Click here</A> to make editorial comments or suggestions.<br />
<br />
<strong><u>Subscriptions:</u></strong><br>
						If you would like to subscribe to LandscapeOnline Weekly, <a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new">click here</a>.
                        <br />
                        <br />
                        If you are no longer in the industry and wish to unsubscribe from LandscapeOnline Weekly, just <a href="mailto:optout_lolweekly@landscapeonline.com?subject=no more news&body=unsubscribe" target="_blank">send us a message</a><br />
                        with the word &quot;unsubscribe&quot; in the body. Cancellation requests may take 7 - 10 business days after your notification. <br />
    <br />
At &nbsp;Landscape Communications, Inc. we are committed to the proper use of email and to protecting consumers from<br />
fraudulent or inappropriate offers.<br />
<a href="https://landscapearchitect.com/research/Ad-Transfer/transfer/Privacy-Policies/LCI-Privacy-Statement.pdf" target="_blank">Privacy Policy</a></td>
			  </tr>
				<TR>
					<TD>
						<img src="/imgz/spacer.gif">					</TD>
			  </TR>
				</TABLE>
	  </td>
	</tr>
</table><br>

 <!-- Social Links -->
	<table width="175">
    	<tr>
        	<td><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:bold">Follow us: </span></td>
        	<td><a href="<? echo $fbook ?>" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/facbook-logo.jpg" width="25" /></a></td>
            <td><a href="<? echo $twitter ?>" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/Twitter_logo_blue.jpg" width="25" /></a></td>
            <td><a href="<? echo $link ?>" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/linkedinicon.jpg" width="25" /></a></td>
    	</tr>
 	</table>       
<? include $include_path . "lol_footer.inc"; ?>
