
<?
include("lo_top-common.inc");
?>

<!-- Menu Section -->  
<div class="main1">

	<!-- Start - Div is here to move the header for the articles in correct position -->
	<div style="position:relative; left:-10px; top:-30px; z-index: 80000">
	    <?
		include $include_path . "lo_header-common.inc";
	?>
 
	</div>

	<!-- Start Content Section -->

	<!-- Start Assoc Search Section -->

<!-- Below used to correct content position need to rewrite to do correct -->
<table>
	<tr>
    	<td style="line-height:5px">&nbsp;</td>
    </tr>
</table>
<!-- Above used to correct content position need to rewrite to do correct -->

<!-- Code Start -->
<div>
	
		<?
			include("lo_banner-common.inc");
		?>




	<table width="1024">
		<tr>
			<td width="240px">
				
				
			<!-- Left Nav Start -->
			

		<?
		include("lo_left-side-common.inc");
		?>	       
	       
	       
		       
			<!-- Left Nav End -->
				
			</td>
			
			
			
			<td width="784">
			
	<div style="position:relative; left: 35px; top: 0px; z-index: 0; width: 700px">
			

	
				<table width="100%" cellpadding="0" cellspacing="0" style="font-size:16px">
				<tr>
					<td>
						<img src="/lol-logos/LO-LOW-logo-325.jpg" width="325" border="0" /><br /><br />
					</td>
				</tr>

				<tr>
					<td>
						<TABLE>
							<TR>
								<TD>
								<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Your Advertising Sales Representative:</span><br>
								<table border="0" cellpadding="" cellspacing="3">
								<tr>
				<td  align="center" width="132">
				If Your Company Name 
				Begins With:</td>
				<td width="266"  align="center" valign="bottom">
				Sales Representative
				</td>
			 </tr>
			
			 <tr>
				<td align="center">
				<strong>A-L</strong>
				</td>
				<td>
				<center>
				<a href="mailto:jmcgehee@landscapeonline.com?subject=LC/DBM Advertising Information Request">James McGehee  - (714) 979-5276 x111</a>
				</center>
				</td>
			 </tr>
			 <tr>
				<td align="center">
				<strong>M-Z</strong>
				</td>
				<td>
				<center>
				<a href="mailto:cphipps@landscapeonline.com?subject=LC/DBM Advertising Information Request">Clint Phipps  - (714) 979-5276 x114</a>
				</center>
				</td>
				</tr>
								</table>								</TD>
							</TR>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
							</TR>
							<tr>
							  <td><span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Information:</span></td>
						  </tr>
							<tr>
							  <td><?= $pubName ?>
								<br />
								14771 Plaza Drive, Suite A
								<br />
								Tustin, CA 92780
								<br />
								(714) 979-5276
								<br />
							  (714) 979-3543	Fax			  </td>
						  </tr>
							<tr>
							  <td><img src="/imgz/spacer.gif" alt="spacer" /></td>
						  </tr>
							<tr>
									<td colspan="3">
								
			<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Subscriptions:</span><br>
									If you would like to subscribe to LandscapeOnline Weekly, <a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new">click here</a>.
									<br />
									<br />
									If you are no longer in the industry and wish to unsubscribe from LandscapeOnline Weekly, just <a href="mailto:optout_lolweekly@landscapeonline.com?subject=no more news&body=unsubscribe" target="_blank">send us a message</a>  with the word &quot;unsubscribe&quot; in the body. Cancellation requests may take 7 - 10 business days after your notification. <br />
				<br />
			At &nbsp;Landscape Communications, Inc. we are committed to the proper use of email and to protecting consumers from fraudulent or inappropriate offers.<br />
			<a href="https://landscapearchitect.com/research/Ad-Transfer/transfer/Privacy-Policies/LCI-Privacy-Statement.pdf" target="_blank">Privacy Policy</a></td>
						  </tr>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
						  </TR>
							</TABLE>
						
						<br>
						<br>
					</td>
				</tr>
			</table>




		
		
	
	
	</div>					
			

				
			
			</td>
			
			
			
		</tr>
	</table><br>
	
	<div style="position: relative; left: 250px">
		<? 	include("lo_top-main2-bottom.inc"); ?>
	</div>
	







<!-- Code End -->


    
	<!-- End Content Section -->
    
</div>
<!-- End Main Section -->
  


</div>





<?
include("lo_footer-main2-new.inc");
?>





