
<?
include("lo_top-main2-prod-js3.inc");
?>

<!-- Menu Section -->  
<div class="main1">

	<!-- Start - Div is here to move the header for the articles in correct position -->
	<div style="position:relative; left:-10px; top:-30px; z-index: 80000">
	    <?
	include $include_path . "lo_header-main2-new.inc";
	?>
 
	</div>

	<!-- Start Content Section -->

	<!-- Start Assoc Search Section -->

<!-- Below used to correct content position need to rewrite to do correct -->
<table>
	<tr>
    	<td style="line-height:5px">&nbsp;</td>
    </tr>
</table>
<!-- Above used to correct content position need to rewrite to do correct -->

<!-- Code Start -->
<div>
	
		<?
			include("lo_top-main2-side2-js50.inc");
		?>




	<table width="1024">
		<tr>
			<td width="240px">
				
				
			<!-- Left Nav Start -->
			

		<?
		include("lo_top-main2-side2-js-banner.inc");
		?>	       
	       
	       
		       
			<!-- Left Nav End -->
				
			</td>
			
			
			
			<td width="784">
			
	<div style="position:relative; left: 35px; top: 0px; z-index: 0; width: 700px">
			

			<table width="100%" cellpadding="0" cellspacing="0" style="font-size:16px">
				<tr>
					<td>
						<img src="/lol-logos/LO-LOW-logo-325.jpg" width="325"><br /><br />
					</td>
				</tr>
				<tr>
					<td>
						<TABLE>
							<TR>
								<TD>
								  <span style="font-family:Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Your Advertising Sales Representative:</span><br>
						  <br />
						  <table align="left" width="763px" border="0" cellpadding="0" cellspacing="0">

								 <tr>
									<td width="15px">
										<strong>A-H</strong>
									</td>
									<td style="width: 10px">
										&nbsp;
									</td>
									<td align="left" width="400px">
										<a href="mailto:jseaberg@landscapeonline.com?subject=LASN Advertising Information Request">Jason Seaberg  - (714) 979-5276 x126</a><br>
									</td>
								 </tr>
								 <tr>
									 <td style="line-height: 10px">&nbsp;</td>
								 </tr>
								 <tr>
									<td width="15px">
										<strong>I-P</strong>
									</td>
									<td style="width: 10px">
										&nbsp;
									</td>						
									<td width="400px">
										<a href="mailto:vchavira@landscapeonline.com?subject=LASN Advertising Information Request">Clint Phipps  - (714) 979-5276 x111</a><br>
									</td>
								 </tr>
								 <tr>
									 <td style="line-height: 10px">&nbsp;</td>
								 </tr>					 
								 <tr>
									<td width="15px" style="position: relative; top: -10px">
										<strong>Q-Z</strong>
									</td>
									<td style="width: 10px">
										&nbsp;
									</td>						
									<td width="400px">
										<a href="mailto:mhenderson@landscapeonline.com?subject=LASN Advertising Information Request">Matt Henderson  - (714) 979-5276 x114</a><br><br>
									</td>
									</tr>                   


								<tr>
									<td colspan="3">
								<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Editorial:</span><br>
									  <A href="https://landscapearchitect.com/research/letter_sub.php">Click here</A> to make editorial comments or suggestions.<br />
			<br />
			<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Subscriptions:</span><br>
									If you would like to subscribe to LandscapeOnline Weekly, <a href="https://landscapearchitect.com/subscriptions/subscribe.php?action=new">click here</a>.
									<br />
									<br />
									If you are no longer in the industry and wish to unsubscribe from LandscapeOnline Weekly, just <a href="mailto:optout_lolweekly@landscapeonline.com?subject=no more news&body=unsubscribe" target="_blank">send us a message</a>  with the word &quot;unsubscribe&quot; in the body. Cancellation requests may take 7 - 10 business days after your notification. <br />
				<br />
			At &nbsp;Landscape Communications, Inc. we are committed to the proper use of email and to protecting consumers from fraudulent or inappropriate offers.<br />
			<a href="https://landscapearchitect.com/research/Ad-Transfer/transfer/Privacy-Policies/LCI-Privacy-Statement.pdf" target="_blank">Privacy Policy</a></td>
						  </tr>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
						  </TR>
							</TABLE>
				  </td>
				</tr>
			</table><br>

		
		
	
	
	</div>					
			

				
			
			</td>
			
			
			
		</tr>
	</table><br>
	
	<div style="position: relative; left: 250px">
		<? 	include("lo_top-main2-bottom.inc"); ?>
	</div>
	







<!-- Code End -->


    
	<!-- End Content Section -->
    
</div>
<!-- End Main Section -->
  


</div>





<?
include("lo_footer-main2-new.inc");
?>





