
<?
include("lo_top-main2-prod-js3.inc");
?>

<!-- Menu Section -->  
<div class="main1">

	<!-- Start - Div is here to move the header for the articles in correct position -->
	<div style="position:relative; left:-10px; top:-30px; z-index: 80000">
	    <?
	include $include_path . "lo_header-main2-new.inc";
	?>
 
	</div>

	<!-- Start Content Section -->

	<!-- Start Assoc Search Section -->

<!-- Below used to correct content position need to rewrite to do correct -->
<table>
	<tr>
    	<td style="line-height:5px">&nbsp;</td>
    </tr>
</table>
<!-- Above used to correct content position need to rewrite to do correct -->

<!-- Code Start -->
<div>
	
		<?
			include("lo_top-main2-side2-js50.inc");
		?>




	<table width="1024">
		<tr>
			<td width="240px">
				
				
			<!-- Left Nav Start -->
			

		<?
		include("lo_top-main2-side2-js-banner.inc");
		?>	       
	       
	       
		       
			<!-- Left Nav End -->
				
			</td>
			
			
			
			<td width="784">
			
	<div style="position:relative; left: 35px; top: 0px; z-index: 0; width: 700px">
			

	
				<table width="100%" cellpadding="0" cellspacing="0" style="font-size:16px">
				<tr>
					<td>
						<img src="<?= $logo ?>" width="325" border="0" /><br /><br />
					</td>
				</tr>

				<tr>
					<td>
						<TABLE>
							<TR>
								<TD>
								<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Your Advertising Sales Representative:</span><br>
								<table border="0" cellpadding="" cellspacing="3">
								<tr>
				<td  align="center" width="132">
				If Your Company Name 
				Begins With:</td>
				<td width="266"  align="center" valign="bottom">
				Sales Representative
				</td>
			 </tr>
			 <tr>
				<td align="center">
				<strong>A-H</strong>
				</td>
				<td>
				<center>
				<a href="mailto:jseaberg@landscapeonline.com?subject=LC/DBM Advertising Information Request">Jason Seaberg  - (714) 979-5276 x126</a>
				</center>
				</td>
			 </tr>
			 <tr>
				<td align="center">
				<strong>I-P</strong>
				</td>
				<td>
				<center>
				<a href="mailto:gschmok@landscapeonline.com?subject=LC/DBM Advertising Information Request">Clint Phipps  - (714) 979-5276 x111</a>
				</center>
				</td>
			 </tr>
			 <tr>
				<td align="center">
				<strong>Q-Z</strong>
				</td>
				<td>
				<center>
				<a href="mailto:mhenderson@landscapeonline.com?subject=LC/DBM Advertising Information Request">Matt Henderson  - (714) 979-5276 x114</a>
				</center>
				</td>
				</tr>
								</table>								</TD>
							</TR>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
							</TR>
							<tr>
							  <td><span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Information:</span></td>
						  </tr>
							<tr>
							  <td><?= $pubName ?>
								<br />
								14771 Plaza Drive, Suite A
								<br />
								Tustin, CA 92780
								<br />
								(714) 979-5276
								<br />
							  (714) 979-3543	Fax			  </td>
						  </tr>
							<tr>
							  <td><img src="/imgz/spacer.gif" alt="spacer" /></td>
						  </tr>
							<tr>
								<td>
									<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Subscriptions:</span><br>
									If you would like to subscribe to <?= $pubName ?>
									or change your address, please send an email to:<br>
									<A href="mailto:circulation@landscapeonline.com">circulation@landscapeonline.com</A></td>
							</tr>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
							</TR>
							<tr>
								<td>
									<p><span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Editorial:</span><br>
									  <a href="https://landscapearchitect.com/research/submissions/index.php">Click here</a> if you would like editorial guidelines, an editorial calendar, or have any questions<br />regarding article submissions.<br>
									  <br />
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">George Schmok</span><br>
									  <em>Publisher/Editor-in-Chief</em><br>
									  <A href="mailto:gschmok@landscapeonline.com">gschmok@landscapeonline.com</a><br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Mike Dahl</span><br />
									  <em>Editor</em><BR>
									  <a href="Mailto:mdahl@landscapeonline.com">mdahl@landscapeonline.com</a><br>
									  (714) 979-5276 ext. 124<br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Alli Rael</span><br>
									  <em>Assistant Editor/Education/Associations</em><br>
									  <a href="Mailto:arael@landscapeonline.com">arael@landscapeonline.com</a><br>
									  (714) 979-5276 ext. 132<br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Nicole Miller</span><br>
									  <em>Art Director</em><br>
									  <a href="Mailto:nmiller@landscapeonline.com">nmiller@landscapeonline.com</a><br>
									  (714) 979-5276 ext. 117<br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Ryan Moore</span><br>
									  <em>Fulfillment</em><br>
									  <a href="Mailto:rmoore@landscapeonline.com">rmoore@landscapeonline.com</a><br>
									  (714) 979-5276 ext. 125<br>
									  <br>                                 


									  </p>
							</td>
				</tr>
						</TABLE>
						<br>
						<br>
					</td>
				</tr>
			</table>




		
		
	
	
	</div>					
			

				
			
			</td>
			
			
			
		</tr>
	</table><br>
	
	<div style="position: relative; left: 250px">
		<? 	include("lo_top-main2-bottom.inc"); ?>
	</div>
	







<!-- Code End -->


    
	<!-- End Content Section -->
    
</div>
<!-- End Main Section -->
  


</div>





<?
include("lo_footer-main2-new.inc");
?>





