<div id='pageBody'>

<table width="100%" cellpadding="0" cellspacing="0">
	<tr>	
		<td>
            <img src="<?= $logo ?>" width="325" border="0" /><br /><br />
		</td>
	</tr>

	<tr>
		<td>
			<TABLE>
				<TR>
					<TD>
					<strong><u>Contact Your Advertising Sales Representative:</u></strong><br>
					<table border="0" cellpadding="" cellspacing="3">
                    <tr>
    <td  align="center" width="132">
    If Your Company Name 
    Begins With:</td>
    <td width="266"  align="center" valign="bottom">
    Sales Representative
    </td>
 </tr>
 <tr>
    <td align="center">
    <strong>A-H</strong>
    </td>
    <td>
    <center>
    <a href="mailto:jseaberg@landscapeonline.com?subject=LASN Advertising Information Request">Jason Seaberg  - (714) 979-5276 x126</a>
    </center>
    </td>
 </tr>
 <tr>
    <td align="center">
    <strong>I-P</strong>
    </td>
    <td>
    <center>
    <a href="mailto:vchavira@landscapeonline.com?subject=LASN Advertising Information Request">Clint Phipps  - (714) 979-5276 x111</a>
    </center>
    </td>
 </tr>
 <tr>
    <td align="center">
    <strong>Q-Z</strong>
    </td>
    <td>
    <center>
    <a href="mailto:mhenderson@landscapeonline.com?subject=LASN Advertising Information Request">Matt Henderson  - (714) 979-5276 x114</a>
    </center>
    </td>
    </tr>
                    </table>					</TD>
				</TR>
				<TR>
					<TD>
						<img src="/imgz/spacer.gif">					</TD>
				</TR>
				<tr>
				  <td><strong><u>Contact Information:</u></strong></td>
			  </tr>
				<tr>
				  <td><?= $pubName ?>
				    <br />
				    14771 Plaza Drive, Suite M
				    <br />
				    Tustin, CA 92780
				    <br />
				    (714) 979-5276
				    <br />
			      (714) 979-3543	Fax			  </td>
			  </tr>
				<tr>
				  <td><img src="/imgz/spacer.gif" alt="spacer" /></td>
			  </tr>
				<tr>
					<td>
						<strong><u>Subscriptions:</u></strong><br>
						If you would like to subscribe to <?= $pubName ?>
						or change your address, please send an email to: <br>
						<A href="mailto:circulation@landscapeonline.com">circulation@landscapeonline.com</A>					</td>
				</tr>
				<TR>
					<TD>
						<img src="/imgz/spacer.gif">					</TD>
				</TR>
				<tr>
					<td>
						<p><strong><u>Editorial:</u></strong><br>
						  <a href="https://landscapearchitect.com/research/submissions/index.php">Click here</a> if you would like editorial guidelines, an editorial calendar, or have any questions regarding article submissions.<br>
                          <br />
						  <strong>George Schmok</strong><br>
						  <em>Publisher/Editor-in-Chief</em><br>
						  <A href="mailto:gschmok@landscapeonline.com">gschmok@landscapeonline.com</a><br>
						  <br>
                          <strong>Stephen Kelly</strong><br />
                          <em>Editor</em><BR>
                          <a href="Mailto:skelly@landscapeonline.com">skelly@landscapeonline.com</a><br>
                          (714) 979-5276 ext. 120<br>
						  <br>
                          <strong>Larry Shield</strong><br>
						  <em>Product Editor</em><br>
						  <a href="Mailto:lshield@landscapeonline.com">lshield@landscapeonline.com</a><br>
                          (714) 979-5276 ext. 125<br>
				          <br>
			    		  <strong><u>Associate Editors</u></strong><br>
						  <strong>Ashley Calabria</strong><br>
						  <em>Associate Editor/Digital Information</em><br>
							University of Georgia<br>
						<A href="mailto:calabria@uga.edu">calabria@uga.edu</A><br>
						<br>
						  <strong>Buck Abbey, ASLA</strong><br>
						  <em>Associate Editor/Ordinances</em><br>
						Louisiana State University<br>
 						<A href="mailto:lsugreenlaws@aol.com">lsugreenlaws@aol.com</A><br>
						<br>
						<strong>Janet Lennox Moyer</strong><br>
						<em>Associate Editor/Lighting</em><br>
						Jan Moyer Design<br>
						<a href="mailto:janmoyerdesign@mac.com">janmoyerdesign@mac.com</a><br />
						<br>
                       </p>
				</td>
	</tr>
			</TABLE>
			<br>
			<br>
		</td>
	</tr>
</table>

 <!-- Social Links -->
	<table width="175">
    	<tr>
        	<td><span style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:bold">Follow us: </span></td>
        	<td><a href="<? echo $fbook ?>" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/facbook-logo.jpg" width="25" /></a></td>
            <td><a href="<? echo $twitter ?>" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/Twitter_logo_blue.jpg" width="25" /></a></td>
            <td><a href="<? echo $link ?>" target="_blank"><img src="https://landscapearchitect.com/lo-logo-s/linkedinicon.jpg" width="25" /></a></td>
    	</tr>
 	</table>       




</div>
<? include $include_path . "lol_footer.inc"; ?>
