

<?
include '../../includes/la_top-common.php';
?>

<!-- Menu Section -->  
<div class="main1">

	<!-- Start - Div is here to move the header for the articles in correct position -->
	<div style="position:relative; left:-10px; top:-30px; z-index: 80000">
	    <?
		include("../../includes/la_header-common.inc");
	?>
 
	</div>

	<!-- Start Content Section -->

	<!-- Start Assoc Search Section -->

<!-- Below used to correct content position need to rewrite to do correct -->
<table>
	<tr>
    	<td style="line-height:5px">&nbsp;</td>
    </tr>
</table>
<!-- Above used to correct content position need to rewrite to do correct -->

<!-- Code Start -->
<div>
	
		<?
			include("../../includes/la_banner-common.inc");

		?>




	<table width="1024">
		<tr>
			<td width="240px">
				
				
			<!-- Left Nav Start -->
			

		<?
		include("../../includes/la_left-side-common2.inc");
		?>	       
	       
	       
		       
			<!-- Left Nav End -->
				
			</td>
			
			
			
			<td width="784">
			
	<div style="position:relative; left: 35px; top: 0px; z-index: 0; width: 700px">
			

	
			
			<table width="100%" cellpadding="0" cellspacing="0" style="font-size:16px">
				<tr>	
					<td>
						<center><img src="<?= $logo ?>" width="700" border="0" /></center><br /><br />
					</td>
				</tr>

				<tr>
					<td>
						<TABLE>
							<TR>
								<TD>
								<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Your Advertising Sales Representative:</span><br>
								<table border="0" cellpadding="" cellspacing="3">
								<tr>
				<td  align="center" width="132">
				If Your Company Name 
				Begins With:</td>
				<td width="266"  align="center" valign="bottom">
				Sales Representative
				</td>
			 </tr>
			 <tr>
				<td align="center">
				<strong>A-L</strong>
				</td>
				<td colspan="5" style="width: 300px;">
				<center>
				<a href="mailto:jmcgehee@landscapearchitect.com?subject=LASN Advertising Information Request">James McGehee  - (714) 979-5276 x111</a>
				</center>
				</td>
			 </tr>
			 <tr>
				<td align="center">
				<strong>M-Z</strong>
				</td>
				<td>
				<center>
				<a href="mailto:cphipps@landscapearchitect.com?subject=LASN Advertising Information Request">Clint Phipps  - (714) 979-5276 x114</a>
				</center>
				</td>
				</tr>
								</table>					</TD>
							</TR>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
							</TR>
							<tr>
							  <td><span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Contact Information: </span></td>
						  </tr>
							<tr>
							  <td><?= $pubName ?>
								<br />
								14771 Plaza Drive, Suite A
								<br />
								Tustin, CA 92780
								<br />
								(714) 979-5276
								<br />
							  (714) 979-3543	Fax			  </td>
						  </tr>
							<tr>
							  <td><img src="/imgz/spacer.gif" alt="spacer" /></td>
						  </tr>
							<tr>
								<td>
									<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Subscriptions:</span><br>
									If you would like to subscribe to <?= $pubName ?> or change your address,<br>
									please send an email to: <br>
									<A href="mailto:circulation@landscapearchitect.com">circulation@landscapearchitect.com</A>					</td>
							</tr>
							<TR>
								<TD>
									<img src="/imgz/spacer.gif">					</TD>
							</TR>
							<tr>
								<td>
									<p><span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold; text-decoration:underline">Editorial:</span><br>
									  <a href="https://landscapearchitect.com/research/submissions/Submit-Editorial.php">Click here</a> if you would like editorial guidelines, an editorial calendar,<br>or have any questions regarding article submissions.<br>
									  <br />
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">George Schmok</span><br>
									  <em>Publisher/Editor-in-Chief</em><br>
									  <A href="mailto:gschmok@landscapearchitect.com">gschmok@landscapearchitect.com</a><br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Mike Dahl</span><br />
									  <em>Editor</em><BR>
									  <a href="Mailto:mdahl@landscapearchitect.com">mdahl@landscapearchitect.com</a><br>
									  (714) 979-5276 ext. 124<br>
									  <br>
									   <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Greg Frank</span><br>
									  <em>Assistant Editor/Education</em><br>
									  <a href="Mailto:gfrankf@landscapearchitect.com">gfrank@landscapearchitect.com</a><br>
									  (714) 979-5276 ext. 132<br>
									  <br>
										<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Allie Lapporte</span><br>
									  <em>Assistant Editor/Associations</em><br>
									  <a href="Mailto:alapporte@landscapearchitect.com">alapporte@landscapearchitect.com</a><br>
									  (714) 979-5276 ext. 139<br>
									  <br> 
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Nicole Miller</span><br>
									  <em>Art Director</em><br>
									  <a href="Mailto:nmiller@landscapearchitect.com">nmiller@landscapearchitect.com</a><br>
									  (714) 979-5276 ext. 117<br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Jeremy Victor</span><br>
									  <em>Ad Coordinator</em><br>
									  <a href="Mailto:jvictor@landscapearchitect.com">jvictor@landscapearchitect.com</a><br>
									  (714) 979-5276 ext. 125<br>
									  <br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold"><u>Associate Editors:</u></span><br><br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Ashley Steffans</span><br>
									  <em>Associate Editor/Technology</em><br>
										University of Georgia<br>
									<A href="mailto:steffans@uga.edu">steffans@uga.edu</A><br>
									<br>
									  <span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Mark Sosnowitz, MG, GCSAA</span><br>
									  <em>Associate Editor/Horticulture &amp; Turf</em><br>
									Mark Eliot Design<br>
									<A href="mailto:msosnowitz@aol.com">msosnowitz@aol.com</A><br>
									<br>
									<span style="font-family:Gotham, 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:bold">Janet Lennox Moyer</span><br>
									<em>Associate Editor/Lighting</em><br>
									Jan Moyer Design<br>
									<a href="mailto:janmoyerdesign@mac.com">janmoyerdesign@mac.com</a><br />
									<br>
								   </p>
							</td>
				</tr>
						</TABLE>
						<br>
						<br>
					</td>
				</tr>
			</table>	




		
		
	
	
	</div>					
			

				
			
			</td>
			
			
			
		</tr>
	</table><br>
	
	<div style="position: relative; left: 250px">
		<? include("../../includes/lo_top-main2-bottom.inc"); ?>
	</div>
	







<!-- Code End -->


    
	<!-- End Content Section -->
    
</div>
<!-- End Main Section -->
  


</div>





<?
    include("../../includes/lo_footer-main2-new.inc");
?>





