<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;CHARSET=x-mac-roman">

<title>

</title>
<style type="text/css">
<!-- 
    a:link {
        color:blue;
        text-decoration:underline;
    }
    a:active { color:red }
    a:visited { color:purple }
    body {
        background-color:white;
        color:black;
    }
    .text0 {
        font-family:'Helvetica','Arial','Sans-serif';
        font-size:11px;
        text-decoration:none;
        color:black;
    }
    .text06 {
        font-family:'Helvetica','Arial','Sans-serif';
        font-size:11px;
    }
    .para0 {
        text-align:left;
    }
    .box1 {
        background-color:white;
        width:763px;
        height:1400px;
    }
    .box2 {
        position:absolute;
        left:430px;
        top:300px;
        padding:0px;
        width:274px;
        height:30px;
    }
    .box3 {
        position:absolute;
        left:528px;
        top:632px;
        padding:0px;
        width:274px;
        height:30px;
    }
    .box4 {
        position:absolute;
        left:285;
        top:692px;
        padding:0px;
        width:274px;
        height:30px;
    }
 -->
</style>
</head>

<body topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">
<table border="0" cellspacing="0" cellpadding="0" align="left">
    <tr>
        <td valign="top" width="763" height="1400">
        <div class="box1">
            <img src="https://landscapearchitect.com/tcart/OnlineStoreLogin/images/store-login-back.jpg" alt=
            "contact-back.jpg" width="763" border="0"></div>
        </td>
    </tr>
    
</table>

<form action="/log-set/login2.php" method="POST">
	<div style="position:absolute; left:450px; top:310px; padding:0px; width:125px">
		<input type="password" name="password" size="16">
	</div>
	<div style="position:absolute; left:450px; top:340px; padding:0px; width:125px; font-size:12px; color:#000; font-weight:bold">
		<input type="submit" name="submit" value="Login">
	</div>
</form>




<form action="mailback.php" method="POST">
	<div style="position:absolute; left:255px; top:495px; padding:0px; width:500px; height:30px">
		<label for="firstname">First name:</label>
		<input type="text" id="firstname" name="firstname" />
	</div>
	<div style="position:absolute; left:255px; top:525px; padding:0px; width:500px; height:30px">
		<label for="lastname">Last name:</label>
		<input type="text" id="lastname" name="lastname" />
	</div>		
<div style="position:absolute; left:245px; top:555px; padding:0px; width:500px; height:30px">
		<label for="email">Email Address:</label>
		<input type="text" id="email" name="email" />
	</div>		
	<div style="position:absolute; left:247px; top:585px; padding:0px; width:500px; height:30px">
		<input type="submit" value="Submit" name="submit" />
	</div>
</form>


	
