 </div>
  
  <div class="center1">
  <div align="center">

 <!-- Add Content Below this line-->
 
<div align="left" style="width: 600px; font-family: Arial, Helvetica, sans-serif; font-size: 15px">
			<br />
           <center>
           <span style="font-size: 24px; font-family:Arial, Helvetica, sans-serif; color:#2474a7"><strong>Contact Us</strong></span>
           </center>
           <br /><br />

<span style="font-size: 20px; font-family:Arial, Helvetica, sans-serif; color:#2474a7"><strong>Produced By</strong></span>
<br /><img width="225" src="https://landscapearchitect.com/lol-logos/LCI-Logo-2013.jpg" border="0"><br /><br />

            <span style="font-size: 18px; font-family:Arial, Helvetica, sans-serif; color:#2474a7">
            <strong> Landscape Communications, Inc.</strong><br></span>
            <span style="font-size: 14px; font-family:Arial, Helvetica, sans-serif">
14771 Plaza Drive, Suite M<br>
Tustin, CA 92780<br>
Ph (714) 979-5276<br>
Fax (714) 508-7591</span>
            <br />
        
	<br />
	<hr align="left" width="90%" noshade="noshade" color="#214262" />
	<br />
    
           
            <center>
            <span style="font-size: 20px; font-family:Arial, Helvetica, sans-serif; color:#2474a7"><strong>LA Expo Contacts</strong></span>
            </center>
            <br /><br />
	<span style="font-size: 18px; font-family:Arial, Helvetica, sans-serif; color:#2474a7">
    <strong>Trade Show Coordination</strong></span><br />
    <span style="font-size: 14px; font-family:Arial, Helvetica, sans-serif">
    Amy Deane<br />
    Ph (714) 979-5276 ext. 142<br />
    Fax (714) 508-7591<br />
    <a href="mailto:adeane@landscapeonline.com">adeane@landscapeonline.com</a></span><br /><br />
    
	<span style="font-size: 18px; font-family:Arial, Helvetica, sans-serif; color:#2474a7">
    <strong>Trade Show Sales</strong></span><br />
    
          	<span style="font-size: 14px; font-family:Arial, Helvetica, sans-serif">
			
            
            Ph (714) 979-5276 ext. 113<br />
            Fax (714) 508-7591<br />
            <a href="mailto:tlesales@landscapeonline.com?subject=LA Expo Booth Information">
            tlesales@landscapeonline.com</a>
            </span>
      

        
          <br /><br />

  


<span style="font-size: 18px; font-family:Arial, Helvetica, sans-serif; color:#2474a7"><strong>Expo Registration</strong></span><br />
<span style="font-size: 14px; font-family:Arial, Helvetica, sans-serif"> Ph (714) 979-5276 ext. 128<br />
Fax (714) 508-7591<br />
<a href="mailto:laxreg@landscapeonline.com">laxreg@landscapeonline.com</a></span><br /><br />


<span style="font-size: 18px; font-family:Arial, Helvetica, sans-serif; color:#2474a7">
<strong>Sponsorships/Special Events</strong></span><br />
<span style="font-size: 14px; font-family:Arial, Helvetica, sans-serif">
Margot Boyer<br />
Ph (714) 979-5276 ext. 143<br />
Fax (714) 979-3543<br />
<a href="mailto:mboyer@landscapeonline.com">mboyer@landscapeonline.com</a></span><br><br />





<br />
	<span style="font-size: 24px; font-family:Arial, Helvetica, sans-serif; color:#2474a7"><strong>
      <a href="https://landscapearchitect.com/" target="_blank">www.LandscapeOnline.com</a><br />
    our network is your network!
    </strong>
    <br />
   
    </span>
</div> 


 
 <!-- Add Content Above this line --> 
</div>
</div>
  
  
  
  
    
  <div class="right1">

<?
include $include_path . "lax-show-right-panel-2015.inc";
?>

  </div>    
  
  <div class="clear"></div>
</div>




<? include $include_path . "lol_footer2-show-lax-2015.inc"; ?>
